apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-cephfs

helmcharts:
  # https://github.com/ceph/ceph-csi
  # https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-cephfs
  # https://artifacthub.io/packages/helm/ceph-csi/ceph-csi-cephfs
  - name: ceph-csi-cephfs
    repo: https://ceph.github.io/csi-charts
    version: 3.14.2
    releaseName: csi-cephfs
    # the storageClass template of the helmchart uses this value
    # to determine where the secrets should live
    namespace: csi-cephfs
    # apparently helm will suppress the generation of CRDs by default 
    #includeCRDs: true
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - poddisruptionbudget.yaml
